### ISSUE TITLE
status of microservice

### ISSUE THREAD

**Issue by use-to** [cryptic-game/server#12]
**Describe the feature you would like**
Later on we have to design a [status page](https://status.cryptic-game.net) of all services in the project.

**Comment by SpartanerSpaten** [comment]
@use-to Is an Ping method in the python3-lib necessary or can you check if the tcp connection is still valid ? When the micro-service is not closing the connection failing hard you would have hard time checking it.

**Comment by JannikEmmerich** [comment]
We already have a discord bot that give status information
