### ISSUE TITLE
Add WebSocket ping/pong instead of info action for heartbeats

### ISSUE THREAD

**Issue by MaxiHuHe04** [cryptic-game/server#13]
**Describe the feature you would like**
As the recommended way, heartbeats should use WebSocket Ping and Pong messages (https://tools.ietf.org/html/rfc6455#section-5.5.2) or at least a specific `heartbeat` action instead of `{"action": "info"}` messages.

**Is your feature request related to a problem? Please describe.**
Currently, the Frontend sends info actions every 30 seconds to keep the connection alive. The Backend responds with 
```
{"name": "username", "online": online_count, "mail": "email", "last": last_login, "created": account_create_time}
```
, which every 30 seconds requested, generates unnecessary much traffic. 

**Additional context**
![image](https://user-images.githubusercontent.com/12913518/58433944-8d556600-80b9-11e9-9eec-6d661295f04c.png)
_Idle traffic in a few minutes_

**Comment by use-to** [comment]
How are statistics such as online number transferred?

**Comment by MaxiHuHe04** [comment]
I mean there should be used something different than the info action for keeping the connection alive and/or checking if the connection is still alive. The info action should not be removed

**Comment by use-to** [comment]
Okay! We should remove it.
