### ISSUE TITLE
password check not working correctly

### ISSUE THREAD

**Issue by use-to** [cryptic-game/server#14]
Work in progress...

**Comment by RedstoneMedia** [comment]
Just use **`(?=.*\d)(?=.*[A-z]).{8,}`** instead of **`^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}`** in this [file](https://github.com/cryptic-game/server/blob/master/src/main/java/net/cryptic_game/server/user/User.java) in the isValidPassword function (line 173)
