### ISSUE TITLE
orm instead of raw sql

### ISSUE THREAD

**Issue by use-to** [cryptic-game/server#19]
**Describe the feature you would like**
We have to use an orm in java instead of raw sql queries.

**Additional context**
Some libs:
- http://hibernate.org/
- https://ebean.io/

**Comment by JannikEmmerich** [comment]
### Server is enhanced from raw sql to orm.
See https://github.com/cryptic-game/server/commit/bd12ae6c664848b213b3e163d123977ca3021f01 for further details.
