### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by janekx21** [cryptic-game/server#31]
**Describe the feature you would like**
Account management options and API implementation
- change password
- delete account

**Is your feature request related to a problem? Please describe.**
You can not change your password or delete your account right now

**Additional context**
related to https://github.com/cryptic-game/frontend/issues/73

**Comment by JannikEmmerich** [comment]
Update: Password change is already implemented

**Comment by Defelo** [comment]
@JannikEmmerich the ms endpoints should be called with `user_uuid` as the only parameter

**Comment by JannikEmmerich** [comment]
The latest commit adds the parameter „user“. Is that fine as well or should I rename the parameter to „user_uuid“?

**Comment by Defelo** [comment]
please rename it to `user_uuid`

**Comment by JannikEmmerich** [comment]
Okay. I‘ll change that.
