### ISSUE TITLE
delete action

### ISSUE THREAD

**Issue by Defelo** [cryptic-game/server#54]
**Describe the bug**
When using the `delete` action the server does not send a response and the user is not deleted.

**Reproduce**
1. Create an account
2. Delete this account by using the `delete` action
3. Login with the same credentials
-> the account still exists

**Logs**
![delete_bug](https://user-images.githubusercontent.com/41747605/87875642-fccf9880-c9d2-11ea-86ab-30cc0ba60244.png)

**Comment by JannikEmmerich** [comment]
@Defelo any logs in the server?

**Comment by Defelo** [comment]
> @Defelo any logs in the server?

https://bin.the-morpheus.de/?715faafbf98c061b#6R4j3F9XgVuDRmKuBxh35c3VJPSSR6h64ULTHs85tYB2
